-- ============================================================
-- Migration 008: Alerts
-- ============================================================
CREATE TABLE IF NOT EXISTS alerts (
    id              SERIAL PRIMARY KEY,
    admission_id    INT NOT NULL REFERENCES admissions(id) ON DELETE CASCADE,
    alert_type      VARCHAR(50) NOT NULL,  -- e.g. 'HIGH_HEART_RATE', 'LOW_SPO2', 'RISK_ESCALATION'
    severity        VARCHAR(20) NOT NULL DEFAULT 'medium'
                    CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    message         TEXT NOT NULL,
    is_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    acknowledged_by INT REFERENCES doctors(id) ON DELETE SET NULL,
    acknowledged_at TIMESTAMPTZ,
    triggered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_alerts_admission ON alerts(admission_id, triggered_at DESC);
CREATE INDEX idx_alerts_unacked   ON alerts(is_acknowledged) WHERE is_acknowledged = FALSE;

COMMENT ON TABLE alerts IS 'Clinical alerts generated by DB triggers when vitals exceed thresholds';
